main: com.bitlimit.PvP.PvP
name: PvP
version: 0.1.1
author: Kolin Krewinkel & Updated by King601
description: BitLimit PVP Plugin
website: http://github.com/BitLimit/PvP/
softdepend: [WorldGuard]
commands:
  map:
    description: WIP - Controls Maps used by BitLimit PvP
    permission: sample.message
    usage: |
      /<command> info.
      /<command> region.
      /<command> idk.
  team:
    description: WIP - Team info used by BitLimit PvP
    usage: /<command> [message]
    permission: sample.message
  match:
    description: WIP - Match info used by BitLimit PvP
    usage: /<command> [message]
    permission: sample.message
  immunity:
    description: Grants immunity to provided player
  admin:
    description: WIP - Match info used by BitLimit PvP
    usage: /<command> [message]
    permission: sample.message

permissions:
  bitlimit.*:
    description: gives all permissions of BitLimit PvP
    default: op
    children:
      bitlimit.message:
        description: gives permission to set the sample message using the sample command